# For more info on HTTP files go to https://aka.ms/vs/httpfile
# For vscode please install rest client 


GET {{HostAddress}}/api/v1/user

###

POST {{HostAddress}}/api/v1/user
Content-Type: application/json

{
   "firstName": "John",
   "lastName": "Emmanuel",
   "otherNames": "HI",
   "email": "john@gmail.com",
   "mobileNumber": "0203254741",
   "password": "123456"
}

###

GET {{HostAddress}}/api/v1/user/aa80dde7-c42b-491c-abe4-065d30710502

###

PUT {{HostAddress}}/api/v1/user/aa80dde7-c42b-491c-abe4-065d30710502
Content-Type: application/json

{
   "firstName": "John",
   "lastName": "Daniel",
   "otherNames": "",
   "email": "john@gmail.com",
   "mobileNumber": "0203254741",
   "password": "123456"
}

###

DELETE {{HostAddress}}/api/v1/user/aa80dde7-c42b-491c-abe4-065d30710502

